name: Terraform

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.0

      - name: Copy Terraform files
        run: |
          find . -type f ! -name 'README.md' ! -name 'main.tf' -exec cp {} $GITHUB_WORKSPACE/ \;

      - name: Initialize Terraform
        run: terraform init

      - name: Apply Terraform
        run: |
          terraform apply -auto-approve
        env:
          AWS_REGION: us-east-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Deploy website
        run: |
          echo "${{ secrets.PEM_KEY }}" > key.pem
          chmod 600 key.pem
          ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@${{ steps.ec2_ip.outputs.ip }} 'sudo yum update -y && sudo yum install -y httpd git && sudo systemctl start httpd && sudo systemctl enable httpd && sudo git clone https://github.com/bibin567/project.git /var/www/html'
        shell: /usr/bin/bash -e {0}
        env:
          TERRAFORM_CLI_PATH: /home/runner/work/_temp/21913d90-304a-47a3-b53d-112377729480

      - name: Get EC2 Public IP
        id: ec2_ip
        run: echo "::set-output name=ip::$(terraform output -raw public_ip)"

      - name: Trigger GitHub Actions workflow
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: 'workflow.yml'
          ref: 'main'
