name: Terraform

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.0

      - name: Copy Terraform files
        run: |
          find . -type f ! -name 'README.md' ! -name 'main.tf' -exec cp {} $GITHUB_WORKSPACE/ \;

      - name: Initialize Terraform
        run: terraform init

      - name: Apply Terraform changes
        run: terraform apply -auto-approve

      - name: Get EC2 Public IP
        id: ec2_ip
        run: echo "::set-output name=ip::$(terraform output public_ip)"

      - name: Deploy website
        run: |
          echo "$PEM_KEY" > key.pem
          chmod 600 key.pem
          ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@${{ steps.ec2_ip.outputs.ip }} 'git clone git@github.com:bibin567/project.git && sudo cp -r project/* /var/www/html/'

      - name: Trigger GitHub Actions workflow
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: 'workflow.yml'
          ref: 'main'
